### ISSUE TITLE
Mob Arena 7, 8, 9 or 10 don't exist in /ma

### ISSUE THREAD

**Issue by Chew** [ChewCraft/SMP#12]
- [x] Mob Arena 7
- [x] Mob Arena 8
- [x] Mob Arena 9
- [x] Mob Arena 10

**Comment by MrJoCrafter** [comment]
Please add this!

**Comment by Chew** [comment]
All mob arenas have been added.

**Comment by Chew** [comment]
Reopening because need to add GUI for them.

**Comment by Chew** [comment]
Alright, now they are fully added and ready to play!
