### ISSUE TITLE
BAN MESSAGE IS BAD

### ISSUE THREAD

**Issue by MrJoCrafter** [ChewCraft/SMP#21]
cuz it says ciphercraft instead of chewcraft!!!!!?!??!!??!?!!?!??!

**Comment by Chew** [comment]
Please provide a picture to help locate the error, thanks!

**Comment by MrJoCrafter** [comment]
![bad](https://cloud.githubusercontent.com/assets/14947881/24579766/1145f0e8-16c1-11e7-8110-03bf94af300e.PNG)
